import Link from 'next/link';
import BudgetLinks from '@/components/store/BudgetLinks';
import ProductCard from '@/components/store/ProductCard';
import SiteFooter from '@/components/store/SiteFooter';
import WhatsAppLink from '@/components/store/WhatsAppLink';
import { getPublicProducts, getSettings } from '@/lib/catalog/public';
import { buildWhatsAppContactMessage } from '@/lib/orders/whatsapp';
import { formatINR } from '@/lib/pricing/money';
import { serializeJsonLd } from '@/lib/json-ld';

export const revalidate = 180;

export async function generateMetadata() {
  return { title: 'Birthday return gifts made easy | JoyBundle', description: 'Curated birthday return gifts in Bangalore, with personalization, simple order requests, and WhatsApp confirmation.', alternates: { canonical: '/' } };
}

export default async function HomePage() {
  const [products, settings] = await Promise.all([getPublicProducts(), getSettings()]);
  const featured = products.filter((product) => product.featured).slice(0, 3);
  const startingPrice = products.length ? products.reduce((lowest, product) => BigInt(product.price_paise) < BigInt(lowest.price_paise) ? product : lowest).price_paise : '0';
  const whatsapp = buildWhatsAppContactMessage({ whatsappNumber: settings.WHATSAPP_NUMBER });
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Organization', name: 'JoyBundle', url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000', areaServed: 'Bangalore' };
  return <main className="min-h-screen overflow-hidden">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(jsonLd) }} />
    <section className="mx-auto flex max-w-6xl flex-col px-5 py-6 sm:px-8 lg:px-12">
      <header className="flex items-center justify-between"><Link href="/" className="text-xl font-bold tracking-tight" aria-label="JoyBundle home">Joy<span className="text-berry">Bundle</span></Link><div className="flex items-center gap-3"><Link href="/track-order" className="text-sm font-bold text-berry">Track Order</Link><span className="rounded-full bg-butter/60 px-3 py-1 text-xs font-semibold">Bangalore</span></div></header>
      <div className="grid items-center gap-10 py-16 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><div><p className="mb-5 text-sm font-bold uppercase tracking-[0.18em] text-berry">Little gifts. Big smiles.</p><h1 className="max-w-xl text-5xl font-bold leading-[1.05] tracking-tight sm:text-7xl">Birthday return gifts made easy.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-ink/70">Curated birthday return gifts for little guests, with personalization available and Bangalore delivery.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#shop" className="inline-flex min-h-12 items-center justify-center rounded-full bg-ink px-6 text-center text-sm font-bold text-white">Shop return gifts</a><a href="#how-it-works" className="inline-flex min-h-12 items-center justify-center rounded-full border-2 border-ink px-6 text-center text-sm font-bold text-ink">How it works</a></div><p className="mt-6 text-sm font-semibold text-ink/65">{startingPrice === '0' ? 'Curated bundles coming soon' : `Starting from ${formatINR(startingPrice)} per gift`} · Bangalore delivery · no payment when you send an order request</p></div><div aria-hidden="true" className="relative mx-auto aspect-square w-full max-w-md"><div className="absolute inset-8 rotate-3 rounded-[38%_62%_55%_45%] bg-peach/80" /><div className="absolute inset-16 -rotate-6 rounded-[55%_45%_38%_62%] bg-mint/90" /><div className="absolute inset-0 flex items-center justify-center"><div className="rounded-3xl border-4 border-ink bg-cream px-8 py-10 text-center shadow-[8px_10px_0_#2e2925]"><div className="text-6xl">🎁</div><p className="mt-4 text-xl font-bold">Made for happy<br />little guests.</p></div></div></div></div>
    </section>
    <section id="shop" className="border-t border-ink/10"><div className="mx-auto max-w-6xl px-5 py-14 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-berry">Shop by budget</p><h2 className="mt-2 text-3xl font-bold">Find the right little surprise.</h2></div><Link href="/shop/under-100" className="text-sm font-bold text-berry">Browse all →</Link></div><div className="mt-6"><BudgetLinks /></div></div></section>
    {featured.length ? <section className="border-t border-ink/10"><div className="mx-auto max-w-6xl px-5 py-14 sm:px-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-berry">Popular bundles</p><h2 className="mt-2 text-3xl font-bold">Thoughtful gifts, ready to make a splash.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featured.map((product) => <ProductCard key={product.product_code} product={product} />)}</div></div></section> : null}
    <section className="border-t border-ink/10"><div className="mx-auto grid max-w-6xl gap-4 px-5 py-14 sm:px-8 md:grid-cols-3"><div className="rounded-2xl bg-peach/50 p-5"><h2 className="font-bold">Made for party days</h2><p className="mt-2 text-sm leading-6 text-ink/70">Curated bundles keep return-gift planning simple.</p></div><div className="rounded-2xl bg-mint/60 p-5"><h2 className="font-bold">Personalized with care</h2><p className="mt-2 text-sm leading-6 text-ink/70">Add a preferred name, age, and short message where available.</p></div><div className="rounded-2xl bg-butter/60 p-5"><h2 className="font-bold">Clear confirmation</h2><p className="mt-2 text-sm leading-6 text-ink/70">We confirm availability, delivery charges, and the final amount on WhatsApp.</p></div></div></section>
    <section id="how-it-works" className="border-t border-ink/10"><div className="mx-auto max-w-4xl px-5 py-14 sm:px-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-berry">How it works</p><h2 className="mt-2 text-3xl font-bold">Five simple steps to party-ready gifts.</h2><ol className="mt-8 grid gap-4 sm:grid-cols-2"><li className="rounded-2xl border border-ink/10 bg-white p-5"><b>1. Choose</b><p className="mt-2 text-sm text-ink/70">Pick a return gift by budget.</p></li><li className="rounded-2xl border border-ink/10 bg-white p-5"><b>2. Tell us</b><p className="mt-2 text-sm text-ink/70">Share quantity and personalization.</p></li><li className="rounded-2xl border border-ink/10 bg-white p-5"><b>3. Confirm</b><p className="mt-2 text-sm text-ink/70">We check availability and delivery charges.</p></li><li className="rounded-2xl border border-ink/10 bg-white p-5"><b>4. Pay manually</b><p className="mt-2 text-sm text-ink/70">We share a QR code on WhatsApp after confirming the final amount.</p></li><li className="rounded-2xl border border-ink/10 bg-white p-5 sm:col-span-2"><b>5. We prepare and deliver</b><p className="mt-2 text-sm text-ink/70">Preparation starts after payment confirmation.</p></li></ol><p className="mt-6 rounded-xl bg-butter/40 p-4 text-sm font-semibold">No payment required when submitting your order request.</p></div></section>
    <section className="border-t border-ink/10"><div className="mx-auto flex max-w-4xl flex-col gap-4 px-5 py-14 sm:px-8 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-bold">Need help choosing?</h2><p className="mt-2 text-sm text-ink/70">Ask JoyBundle about bundles, personalization, or your party date.</p></div><WhatsAppLink href={whatsapp?.url} className="inline-flex min-h-12 items-center justify-center rounded-full bg-ink px-6 text-sm font-bold text-white">Continue on WhatsApp</WhatsAppLink></div></section>
    <SiteFooter whatsappUrl={whatsapp?.url || ''} />
  </main>;
}
